title: Quantum Hazel
email: tom.jira@gmail.com
github_username: jirat

url: "https://tjira.github.io"
baseurl: "/hazel"

description: >-
  Quantum Hazel is a quantum mechanical software packaged in a single executable.
  Similarly as other quantum programs you provide the program with a geometry file, the calculation options are specified in the command line.
  The output will be printed into the terminal.

plugins:
  - jekyll-remote-theme

remote_theme: just-the-docs/just-the-docs

aux_links:
  "Quantum Hazel on GitHub":
    - "//github.com/tjira/hazel"

callouts:
  note:
    color: blue
