name: Release

on:
  push:
    tags:
      - 'v**'

permissions:
  contents: write

env:
  BUILD_TYPE: Release

jobs:
  release_linux_x86-64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Packages
        run: sudo apt install -y libboost-all-dev libeigen3-dev

      - name: Build Libint
        run: ./script/libint.sh

      - name: Configure Hazel
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DGOMP=OFF

      - name: Build Hazel
        run: |
          export CPLUS_INCLUDE_PATH="$PWD/libint/install/include:$CPLUS_INCLUDE_PATH"
          export LIBRARY_PATH="$PWD/libint/install/lib:$LIBRARY_PATH"
          cmake --build build --parallel 2

      - name: Move the Executable to Root
        run: mv bin/hazel .

      - name: Remove Redundant Scripts
        run: rm basis/basis.sh example/molecule/optimize.sh example/trajectory/trajectory.sh

      - name: Create Package
        run: tar -czf hazel_linux_x86-64.tar.gz hazel basis example

      - name: Release Linux Version of Hazel
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: hazel_linux_x86-64.tar.gz
          tag: ${{github.ref}}

  release_win64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure Hazel
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DGOMP=OFF -DSTANDALONE=ON -G "Unix Makefiles"

      - name: Build Hazel
        run: cmake --build build --parallel 2

      - name: Move the Executable to Root
        run: mv bin/hazel.exe .

      - name: Remove Redundant Scripts
        run: rm basis/basis.sh example/molecule/optimize.sh example/trajectory/trajectory.sh

      - name: Create Package
        run: zip -r hazel_win64.zip hazel.exe basis example

      - name: Release Windows Version of Hazel
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: hazel_win64.zip
          tag: ${{github.ref}}
