name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Packages
        run: sudo apt install -y libboost-all-dev libeigen3-dev

      - name: Build Libint
        run: ./script/libint.sh

      - name: Configure Hazel
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build Hazel
        run: |
          export CPLUS_INCLUDE_PATH="$PWD/libint/install/include:$CPLUS_INCLUDE_PATH"
          export LIBRARY_PATH="$PWD/libint/install/lib:$LIBRARY_PATH"
          cmake --build build --parallel 2

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: bin/hazel

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure Hazel
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSTANDALONE=ON -G "Unix Makefiles"

      - name: Build Hazel
        run: cmake --build build --parallel 2

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: bin/hazel.exe

  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]

    steps:
      - uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3

      - name: Copy Binaries to the Root Folder
        run: cp artifact/hazel artifact/hazel.exe ${{github.workspace}}

      - name: Create Packages
        run: |
          tar -czf hazel-linux-amd64.tar.gz hazel basis example
          zip -r hazel-windows.zip hazel.exe basis example

      - name: Release Linux Version of Hazel
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: hazel-linux-amd64.tar.gz
          tag: ${{github.ref}}

      - name: Release Windows Version of Hazel
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: hazel-windows.zip
          tag: ${{github.ref}}
