name: Release

on:
  push:
    tags:
      - 'v**'

permissions:
  contents: write

env:
  BUILD_TYPE: Release

jobs:
  build_linux_x86-64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Packages
        run: sudo apt install -y libboost-all-dev libeigen3-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev

      - name: Build Libint
        run: ./script/libint.sh

      - name: Configure Hazel
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DAVX=ON -DGOMP=OFF

      - name: Build Hazel
        run: |
          export CPLUS_INCLUDE_PATH="$PWD/libint/install/include:$CPLUS_INCLUDE_PATH"
          export LIBRARY_PATH="$PWD/libint/install/lib:$LIBRARY_PATH"
          cmake --build build --parallel 2

      - name: Rename Executable
        run: mv bin/hazel bin/hazel_linux_x86-64 && mv bin/hview bin/hview_linux_x86-64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            bin/hazel_linux_x86-64
            bin/hview_linux_x86-64

  build_linux_x86-64_openmp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Packages
        run: sudo apt install -y libboost-all-dev libeigen3-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev

      - name: Build Libint
        run: ./script/libint.sh

      - name: Configure Hazel
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DAVX=ON -DGOMP=ON

      - name: Build Hazel
        run: |
          export CPLUS_INCLUDE_PATH="$PWD/libint/install/include:$CPLUS_INCLUDE_PATH"
          export LIBRARY_PATH="$PWD/libint/install/lib:$LIBRARY_PATH"
          cmake --build build --parallel 2

      - name: Rename Executable
        run: mv bin/hazel bin/hazel_linux_x86-64_openmp && mv bin/hview bin/hview_linux_x86-64_openmp

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            bin/hazel_linux_x86-64_openmp
            bin/hview_linux_x86-64_openmp

  build_windows_x86-64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Packages
        run: pip install jinja2

      - name: Configure Hazel
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DAVX=ON -DGOMP=OFF -DSTANDALONE=ON -G "Unix Makefiles"

      - name: Build Hazel
        run: cmake --build build --parallel 2

      - name: Rename Executable
        run: mv bin/hazel.exe bin/hazel_windows_x86-64.exe && mv bin/hview.exe bin/hview_windows_x86-64.exe

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            bin/hazel_windows_x86-64.exe
            bin/hview_windows_x86-64.exe

  release:
    runs-on: ubuntu-latest
    needs: [build_linux_x86-64, build_linux_x86-64_openmp, build_windows_x86-64]

    steps:
      - uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3

      - name: Remove Redundant Scripts
        run: rm basis/basis.sh example/generate.inp

      - name: Copy x86-64 Binaries to the Root Folder
        run: |
          cp artifact/hazel_linux_x86-64 hazel && cp artifact/hazel_windows_x86-64.exe hazel.exe
          cp artifact/hview_linux_x86-64 hview && cp artifact/hview_windows_x86-64.exe hview.exe

      - name: Create x86-64 Packages
        run: |
          zip -r hazel_windows_x86-64.zip hazel.exe hview.exe basis example LICENSE.md
          tar -czf hazel_linux_x86-64.tar.gz hazel hview.exe basis example LICENSE.md

      - name: Copy x86-64_openmp Binaries to the Root Folder
        run: |
          cp artifact/hazel_linux_x86-64_openmp hazel
          cp artifact/hview_linux_x86-64_openmp hview

      - name: Create x86-64_openmp Packages
        run: |
          tar -czf hazel_linux_x86-64_openmp.tar.gz hazel hview basis example LICENSE.md

      - name: Release linux_x86-64 Version of Hazel
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: hazel_linux_x86-64.tar.gz
          tag: ${{github.ref}}

      - name: Release linux_x86-64_openmp Version of Hazel
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: hazel_linux_x86-64_openmp.tar.gz
          tag: ${{github.ref}}

      - name: Release windows_x86-64 Version of Hazel
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: hazel_windows_x86-64.zip
          tag: ${{github.ref}}
