name: Test

on:
  push:
    branches:
      - 'master'

permissions:
  contents: write

env:
  BUILD_TYPE: Release

jobs:
  test_linux_x86-64_openmp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Packages
        run: sudo apt install -y libboost-all-dev libeigen3-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev

      - name: Build Libint
        run: ./script/libint.sh

      - name: Configure Hazel
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DGOMP=ON

      - name: Run Tests
        working-directory: build
        run: |
          export CPLUS_INCLUDE_PATH="$PWD/../libint/install/include:$CPLUS_INCLUDE_PATH"
          export LIBRARY_PATH="$PWD/../libint/install/lib:$LIBRARY_PATH"
          ctest --verbose
