name: Test

on:
  push:
    branches: ["master"]

permissions:
  contents: write

env:
  BUILD_TYPE: Release

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Packages
        run: sudo apt install -y libboost-all-dev libeigen3-dev

      - name: Build Libint
        run: ./script/install/libint.sh

      - name: Configure Hazel
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build Tests
        run: |
          export CPLUS_INCLUDE_PATH="$PWD/libint/install/include:$CPLUS_INCLUDE_PATH"
          export LIBRARY_PATH="$PWD/libint/install/lib:$LIBRARY_PATH"
          cmake --build build --target test_hazel

      - name: Run Tests
        working-directory: build
        run: ctest --verbose
